"""lmn-gpo — GPO template toolkit for linuxmuster.net 7.x (Samba AD DC)."""
from __future__ import annotations

import os
import re


def _read_version() -> str:
    """The version is written once, in debian/changelog; nothing in the code repeats it.

    The installed package carries lmn_gpo/_version.py, generated by debian/rules
    (a plain dist-packages install has no distribution metadata for importlib.metadata).
    A source checkout reads the changelog's first line, like dpkg-parsechangelog does.
    """
    try:
        from ._version import __version__ as installed
        return installed
    except ImportError:
        pass
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    try:
        with open(os.path.join(repo, "debian", "changelog"), encoding="utf-8") as fh:
            m = re.match(r"^\S+ \(([^)]+)\) ", fh.readline())
    except OSError:
        m = None
    return m.group(1) if m else "0+unknown"


__version__ = _read_version()
