#!/bin/sh
# Build the lmn-gpo .deb from this source tree using dpkg-deb.
# Needs dpkg-dev (dpkg-parsechangelog, dpkg-deb) and a POSIX shell; no debhelper, no root.
# The version is the top entry of debian/changelog, the single version source; it is
# written into the control file and into lmn_gpo/_version.py of the package.
#
#   packaging/build-deb.sh [OUTPUT_DIR]      # default: <repo>/dist   (or: make deb)
set -e

HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/.." && pwd)
PKG=lmn-gpo
VERSION=$(dpkg-parsechangelog -l "$REPO/debian/changelog" -S Version)
[ -n "$VERSION" ] || { echo "no version in $REPO/debian/changelog" >&2; exit 1; }
grep -q '^Version: @VERSION@$' "$HERE/control" \
    || { echo "packaging/control must carry 'Version: @VERSION@' (the changelog fills it)" >&2; exit 1; }
ARCH=all
OUTDIR=${1:-$REPO/dist}

STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT
ROOT="$STAGE/$PKG"

echo "Building $PKG $VERSION ($ARCH) ..."

# ---- file tree -----------------------------------------------------------
install -d "$ROOT/DEBIAN" \
           "$ROOT/usr/bin" \
           "$ROOT/usr/lib/python3/dist-packages/lmn_gpo" \
           "$ROOT/usr/share/$PKG" \
           "$ROOT/usr/share/doc/$PKG" \
           "$ROOT/var/lib/$PKG/wallpapers"

# Python module (source .py only; no __pycache__)
for f in "$REPO"/lmn_gpo/*.py; do
    install -m 644 "$f" "$ROOT/usr/lib/python3/dist-packages/lmn_gpo/"
done
# The installed module has no distribution metadata, so it learns its version from this
# generated file; a source checkout reads debian/changelog instead (lmn_gpo/__init__.py).
printf '"""Generated by packaging/build-deb.sh from debian/changelog -- do not edit."""\n__version__ = "%s"\n' \
    "$VERSION" > "$ROOT/usr/lib/python3/dist-packages/lmn_gpo/_version.py"

# Read-only data shared by the toolkit
cp -a "$REPO/catalog" "$ROOT/usr/share/$PKG/catalog"
cp -a "$REPO/scripts" "$ROOT/usr/share/$PKG/scripts"
cp -a "$REPO/lib"     "$ROOT/usr/share/$PKG/lib"

# CLI launcher -> /usr/bin/lmn-gpo
cat > "$ROOT/usr/bin/$PKG" <<'PY'
#!/usr/bin/env python3
"""Command-line entry point for the lmn-gpo toolkit."""
import sys

from lmn_gpo.cli import main

if __name__ == "__main__":
    sys.exit(main())
PY

# Documentation
install -m 644 "$REPO/README.md" "$ROOT/usr/share/doc/$PKG/README.md"
[ -d "$REPO/docs" ] && cp -a "$REPO/docs" "$ROOT/usr/share/doc/$PKG/docs"
install -m 644 "$HERE/copyright" "$ROOT/usr/share/doc/$PKG/copyright"
gzip -9nc "$REPO/debian/changelog" > "$ROOT/usr/share/doc/$PKG/changelog.Debian.gz"

# ---- normalise ownership-independent permissions -------------------------
find "$ROOT/usr" "$ROOT/var" -type d -exec chmod 755 {} +
find "$ROOT/usr" "$ROOT/var" -type f -exec chmod 644 {} +
chmod 755 "$ROOT/usr/bin/$PKG"

# ---- control + maintainer scripts ---------------------------------------
INSTKB=$(du -k -s --exclude=DEBIAN "$ROOT" | cut -f1)
{ sed "s/^Version: @VERSION@$/Version: $VERSION/" "$HERE/control"; echo "Installed-Size: $INSTKB"; } > "$ROOT/DEBIAN/control"
for s in postinst prerm postrm; do
    install -m 755 "$HERE/$s" "$ROOT/DEBIAN/$s"
done
# md5sums of every shipped file (what dh_md5sums would write): without it `dpkg --verify
# lmn-gpo` has nothing to check and lintian reports no-md5sums-control-file. Paths are
# relative to the package root without a leading ./, as dpkg expects.
( cd "$ROOT" && find . -type f -not -path './DEBIAN/*' -printf '%P\n' | LC_ALL=C sort \
      | xargs -d '\n' md5sum ) > "$ROOT/DEBIAN/md5sums"
chmod 644 "$ROOT/DEBIAN/md5sums"

# ---- build ---------------------------------------------------------------
mkdir -p "$OUTDIR"
DEB="$OUTDIR/${PKG}_${VERSION}_${ARCH}.deb"
dpkg-deb --root-owner-group --build "$ROOT" "$DEB"
echo "Built: $DEB"
